# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d4acc3ccb431965aead49eb351eb5684c2824f395478a4884e5ce803129570644618ab394743437ce63c80857a6b0b37d2a15c47247060d61b6918616ce859

test:
  secret_key_base: a57073f753b107404b20797308d73b68fc74065e6a42edee966293d48fea91cf22a356e82c2023cc8707fd98ed9f01ac7373ff5593d29e36d9e8ba8dd6e3de58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
